version: "3.1"

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app/frontend
      - frontend_node_modules:/app/frontend/node_modules
  backend:
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    build:
      context: ./backend
      dockerfile: Dockerfile.backend.dev
    ports:
      - "8082:8082"
    env_file:
      - .env
    command: >
      sh -c "cargo sqlx migrate run && cargo run"
    volumes:
      - ./backend:/app
      - cargo-target:/app/target
      - cargo-registry:/usr/local/cargo/registry
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3308:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "3307:3307"
    depends_on:
      - mariadb

volumes:
  cargo-target:
  cargo-registry:
  mariadb_data:
  frontend_node_modules:
