FROM rust:latest

WORKDIR /app

# cargo-watch をインストール
RUN cargo install cargo-watch

# ソースをコピー（最初だけ）
COPY . .

RUN cargo install sqlx-cli --no-default-features --features mysql

# 必要なポートを公開
EXPOSE 8080

# ファイルを監視して自動ビルド＆実行
CMD ["cargo", "watch", "-x", "run"]
