CREATE TABLE tags (
  id       BIGINT AUTO_INCREMENT PRIMARY KEY,
  name     VARCHAR(100),
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
