-- Add up migration script here
CREATE TABLE cards (
  id       BIGINT AUTO_INCREMENT PRIMARY KEY,
  title    VARCHAR(100),
  contents TEXT,
  shape    POLYGON    NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  SPATIAL INDEX idx_shape (shape)
)
